title: Flame Transfer Function Tutorials
description: MATLAB/OCTAVE tutorials to learn the basics of thermoacosutics.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

github:
  zip_url: https://github.com/xoeg/Flame-Transfer-Function-Tutorial/zipball/main
  tar_url: https://github.com/xoeg/Flame-Transfer-Function-Tutorial/tarball/main
