title: Annulight Workshop 4 - Flame Transfer Functions - Theory, analysis and application
description: MATLAB tutorials
show_downloads: true
google_analytics: G-8G76PFS1PE
theme: jekyll-theme-cayman

github:
  zip_url: https://github.com/xoeg/Flame-Transfer-Function-Tutorial/zipball/main
  tar_url: https://github.com/xoeg/Flame-Transfer-Function-Tutorial/tarball/main
